demo/app/app.template.html, src/components/dialog/dialog.service.ts, src/components/drawer/drawer.service.ts, src/components/overlay/overlay.service.ts, src/components/toggle/toggle.component.ts
=> Fix: drawers being closed when date closes, wrong overlay z-index

demo/app/app.template.html, src/components/overlay/overlay.component.scss, src/components/overlay/overlay.component.ts
=> feature(overlay): Show content and demo

demo/app/app.component.ts, demo/app/app.template.html, src/components/button/button.component.scss, src/components/button/button.component.ts
When in a waiting state:
- disable only click pointer event
- show wait cursor
=> Button states, pointer events

CHANGELOG.md, demo/app/app.template.html, src/components/split/split-area.directive.ts, src/components/split/split-handle.component.ts, src/components/split/split.component.ts
* Feature: Add minAreaPct and maxAreaPct inputs to ngxSplitArea
* Feature: Add double-click event to ngx-split-handle component
* Feature: Add double click split handle to snap to extremes
* Bug: Each ngxSplit now only listens to direct child ngx-split-handles
=> feature(splitter): Add max/min and double click feature

CHANGELOG.md, demo/app/app.template.html, src/components/code-editor/code-editor.component.scss, src/components/input/input.component.scss, src/components/select/select.component.scss
=> Fix: ensure form elemments have correct margin and padding per md spec

CHANGELOG.md, demo/app/app.template.html, src/styles/components/loading.scss
https://www.screencast.com/t/xw2Bt9SP
=> Updated preloader to respond during JS load, fixes #68

demo/app/app.component.ts, src/components/date-time/date-time.component.ts
* Pass hints down from ngx-date-time to ngx-input
* If date in ngx-date-time is invalid use current date in calendar view.
=> Add hint to dateTimePicker and use current date if date is invalid

demo/app/app.template.html, src/components/input/input.component.ts, src/components/select/select.component.scss, src/components/select/select.component.ts
=> Fix overlapping labels and placeholders

demo/app/app.template.html, src/styles/components/buttons.scss
Adds small and large button classes
Updates demo page to display different button sizes
=> (feat): Add button size classes

demo/app/app.template.html, src/components/dropdown/dropdown.component.scss, src/components/dropdown/dropdown.component.ts
Adds `showCaret` input to dropdown component
=> (feat): Add showCaret input to dropdowns

demo/app/app.template.html, src/styles/components/tags.scss
=> (feat): Update tag styles

CHANGELOG.md, demo/app/app.component.scss, demo/app/app.component.ts, demo/app/app.template.html, src/styles/fonts/source-sans.scss
=> Added light and light italic fonts

package.json, src/components/split/split-area.directive.ts, src/components/split/split.component.ts, src/services/injection.service.ts
- upgrades project to angular 5
- upgrades flex-layout
=> Upgrade to angular 5

CHANGELOG.md, demo/app/app.component.scss, demo/app/app.component.ts, demo/app/app.template.html, src/components/input/input.component.scss, src/components/input/input.component.ts, src/components/nag/nag.component.ts, src/components/select/select-input.component.ts, src/components/select/select.component.scss, src/components/select/select.component.ts, src/styles/colors/gradients.scss, src/styles/forms/inputs.scss
* Replace color gradients
* Nag component stateChanged -> stateChange
* Fixed disable component colors
=> Styles, gradients, and more

.gitignore, cypress.json, cypress/fixtures/example.json, cypress/integration/basic-spec.js, cypress/support/commands.js, cypress/support/index.js, package.json
=> Chore: adding cypress.io to test demo app

src/components/button/file-button.component.ts
Add option for multiple file selection
=> Add option for multiple file selection

CHANGELOG.md, package-lock.json, src/components/calendar/calendar.component.ts, src/components/date-time/date-time.component.ts
* Fixes #21, clicking current on date select does not switch view to current day
* Fixes issue where min and hour inputs and model get out of sync in date+time dialog.
=> Fixed date/time selection, Fixes #21

src/components/tooltip/tooltip.directive.ts
=> Add nullcheck in showTooltip to check whether element still exists

src/components/button/button.component.scss, src/styles/components/buttons.scss
Fixes button padding and icon sizes.
=> (fix): Fix button padding

demo/app/app.template.html, src/components/select/select-dropdown.component.ts, src/components/select/select-input.component.ts, src/components/select/select.component.scss, src/components/select/select.component.ts
* Add styling for invalid state
* Add check for required and minSelections.
* Allow custom `allowAdditionsText`
* Allow custom drop-down caret
=> Improvments to ngx-select

cypress/integration/basic-spec.js, demo/app/app.component.ts, demo/app/app.template.html, src/components/input/input.component.scss, src/components/input/input.component.ts, src/components/select/select.component.scss
* Show invalid state when input has a value
* Adjusts invalid label weight
* Adjusts invalid hint color
=> Improve invalid state for ngx-input

projects/swimlane/ngx-ui/src/lib/components/drawer/drawer.component.scss, projects/swimlane/ngx-ui/src/lib/components/drawer/drawer.component.ts, projects/swimlane/ngx-ui/src/lib/components/drawer/drawer.service.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.ts, src/app/dialogs/drawer-page/drawer-page.component.html, src/app/dialogs/drawer-page/drawer-page.component.ts
Addresses #103 and #105 
#105 
- if `!closeOnOutsideClick`, disable close on outside click and add a close button
- Additional demo section is added
=> #103, #105

package-lock.json, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/input/input.component.ts
* `setDisabledState` required for functionality with reactive forms `FormControl`.
=> Fix: ngx-input now implements setDisabledState per ControlValueAccessor

projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.ts
=> set toggle value to false if undefined #231

projects/swimlane/ngx-ui/src/lib/styles/components/buttons.scss, projects/swimlane/ngx-ui/src/lib/styles/index.scss, src/app/forms/buttons-page/buttons-page.component.html
=> add btn-primary-gradient class #233

projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.ts
Decades view was not updating when a new value is selected.
=> Calendar decades bug fix

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-option.directive.ts, src/app/forms/selects-page/selects-page.component.html
=> added hidden attribute in select option

package-lock.json, package.json, projects/swimlane/ngx-ui/package-lock.json, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.helper.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/object-node.component.ts
Adds support for mulitple types for array items
=> JSON editor array multitypes

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts
=> Current hide #254

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/split/split-area.directive.ts
Extra null check to avoid error.
=> Fixing splitAreaDirective error

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.component.scss
=> prevent line break in json editor

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/notification/notification.component.scss
https://swimlane.atlassian.net/browse/ST-608
=> add overflow on notification body

projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.ts
- Adds more null checks in the template
- Always calls update icons and schema inference when there are changes in the array node component
=> Fix JSON editor issues

projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.ts
- min and max dates accept string
- handling invalid date
=> allow string values of min and max, validate date

projects/swimlane/ngx-ui/src/lib/ngx-ui.module.ts
Appears to be missed import for #207 and #217
=> Fix radio button export

projects/swimlane/ngx-ui/src/lib/components/dialog/alert/alert.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/alert/alert.component.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/alert/alert.service.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/alert/alert.service.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.module.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.service.spec.ts, src/app/dialogs/alert-page/alert-page.component.html
Extra optional parameter added to alertService.confirm(...) to allow longPress confirmation for destructive actions.
=> add longPress option to alert confirmation

projects/swimlane/ngx-ui/src/lib/directives/directives.module.ts, projects/swimlane/ngx-ui/src/lib/directives/validators/pattern-validator.directive.ts, src/app/forms/inputs-page/inputs-page.component.html, src/app/forms/inputs-page/inputs-page.component.ts
=> Add pattern validator

projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.ts
Allow change event to emit even if current day hasn't changed
=> ngx-calendar change event

package-lock.json, package.json, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.component.ts, projects/swimlane/ngx-ui/src/lib/services/injection.service.ts
Updates the injection service to use CDK portals
=> Change InjectionService to use portals

projects/swimlane/ngx-ui/src/lib/components/dialog/alert/alert.component.ts
=> disable keydown when longpress is true

projects/swimlane/ngx-ui/src/lib/components/calendar/calender.component.spec.ts
fix test that fails if current month is last of year
=> if month is last of year, next month is index 0

projects/swimlane/ngx-ui/src/lib/components/input/input.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/loading/loading.component.ts, projects/swimlane/ngx-ui/src/lib/components/long-press/index.ts, projects/swimlane/ngx-ui/src/lib/components/long-press/long-press-button-state.enum.ts, projects/swimlane/ngx-ui/src/lib/components/long-press/long-press-button.component.html, projects/swimlane/ngx-ui/src/lib/components/long-press/long-press-button.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/long-press/long-press-button.component.ts, projects/swimlane/ngx-ui/src/lib/directives/long-press.directive.ts
Summary:
- change long-press button to on-push
- reorganize code
- coerce inputs
- bring unit test coverage to 100%
- fix occasionally failing InputComponent tests
- add exportAs to missing previous components
=> Aacebo/long press  on push

projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/input/input-autosave.directive.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/input/input-autosize.directive.spec.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/radiobutton/radiobutton-group.component.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/radiobutton/radiobutton-group.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/radiobutton/radiobutton-group.component.ts, projects/swimlane/ngx-ui/src/lib/components/radiobutton/radiobutton.component.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/radiobutton/radiobutton.component.html, projects/swimlane/ngx-ui/src/lib/components/radiobutton/radiobutton.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/radiobutton/radiobutton.component.ts, src/app/forms/radio-page/radio-page.component.ts
Summary:
- make components on-push
- coerce inputs
- unit test for coverage
- break test host components out into fixture files
=> Aacebo/radiobutton  on push

projects/swimlane/ngx-ui/src/lib/components/button/button.component.html, projects/swimlane/ngx-ui/src/lib/components/button/button.component.ts, projects/swimlane/ngx-ui/src/lib/components/button/file-button.component.html, projects/swimlane/ngx-ui/src/lib/components/button/file-button.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/button/file-button.component.ts, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.spec.ts
Summary:
- change detection on-push
- move markup to html files
- cleanup markup
- input coercion and typing added
=> Aacebo/file upload button  on push

projects/swimlane/ngx-ui/src/lib/components/nav-menu/nav-menu.component.html, projects/swimlane/ngx-ui/src/lib/components/nav-menu/nav-menu.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/nav-menu/nav-menu.component.ts
Summary: 
- make on-push
- coerce input
- move markup to html file
=> change to on-push and coerce input

projects/swimlane/ngx-ui/src/lib/components/icon/icon.component.html, projects/swimlane/ngx-ui/src/lib/components/icon/icon.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/icon/icon.component.ts, src/app/components/ngx-icon-page/ngx-icon-page.component.ts
Summary:
- move markup to html file
- cleanup unused vars
- unit test
=> cleanup code and unit test

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.component.scss
Tested this locally and it's working for me.
=> #372: fix button styling on .ngx-tabs

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-node.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.ts, src/app/components/json-editor-page/json-editor-page.component.ts
Summary:
- when examples array is defined in schema it should be used as placeholder for node if possible
issue: https://github.com/swimlane/ngx-ui/issues/262
=> Aacebo/json editor  examples placeholder

projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.html, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.scss, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.ts, src/app/forms/checkbox-page/checkbox-page.component.html
Summary:
- update checkbox styles based on Figma
- add better animation
- add round input
- coerce all inputs necessary
=> SPT-5847/round-checkbox

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-types.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/property-config/property-config.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/property-config/property-config.component.ts, src/app/components/json-editor-page/json-editor-page.component.ts
Allow the edition of title and description of root schema object
=> Json Editor Schema Builder: Support edit of root object

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.ts
Added 1s delay on mouseleave event for dropdown to prevent closing in incedental mouseleave.
=> Enhancement: delay closeOnMouseLeave in dropdown

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/orderable-inputs-list/orderable-inputs-list.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/orderable-inputs-list/orderable-inputs-list.component.ts
Fix examples bug and move schemRef init to OnChanges
=> JSON Editor bug fixes

projects/swimlane/ngx-ui/src/lib/components/input/input.component.scss
Fixes minor CSS typo.  Might cause issues in places that worked around this.
=> Fix css in input control.

projects/swimlane/ngx-ui/package.json
* The JSON tree is implemented with recursive components which experence an bug in prod.  Work around is to allow side effects in ngx-ui's package.json.
https://github.com/angular/angular/issues/35602
=> Allow side effects

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/icon/icon.module.ts
=> (release): 28.5.7

package.json, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/input/input.component.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts, projects/swimlane/ngx-ui/src/lib/components/tooltip/tooltip.directive.ts, projects/swimlane/ngx-ui/src/lib/directives/long-press/long-press.directive.ts, src/app/forms/inputs-page/inputs-page.component.html
* For numeric inputs, coerce invalid input to null
* Select min/max selections defualt to undefined
* Other values defualt to the default value
_\*required_
=> Fix numeric coercion

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tabs/tab.component.ts, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.ts, src/app/components/tabs-page/tabs-page.component.html, src/app/components/tabs-page/tabs-page.component.ts
* Setup watcher in tabs component watching for any changes to the tab inputs
* Fixes #436
_\*required_
=> Fix for tab buttons to updating with disabled input, fixes #436

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 28.6.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
* release patch version
_\*required_
=> (release): 28.6.1

README.md
* Add pushing tags to readme release process
_\*required_
=> git push tags in readme

src/app/components/json-editor-page/json-editor-page.component.html, src/app/components/overlay-page/overlay-page.component.html, src/app/components/tree-page/tree-page.component.html, src/app/dialogs/nag-page/nag-page.component.html
- Fix mangled examples that were mangled by prettier
_\*required_
=> Fix mangled examples

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 28.7.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
(release): 29.0.0
_\*required_
=> (release): 29.0.0

README.md, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/split/split.directive.ts
=> (release): 29.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/drawer/drawer.component.scss, projects/swimlane/ngx-ui/src/lib/services/injection/injection.service.ts, src/app/app.module.ts, src/app/dialogs/drawer-page/drawer-container-example/drawer-container-example.component.html, src/app/dialogs/drawer-page/drawer-container-example/drawer-container-example.component.scss, src/app/dialogs/drawer-page/drawer-container-example/drawer-container-example.component.ts, src/app/dialogs/drawer-page/drawer-page.component.html, src/app/dialogs/drawer-page/drawer-page.component.scss, src/app/dialogs/drawer-page/drawer-page.component.ts
- make context drawer compatible with components
- make example more verbose/clear
- fix ngx-drawer-content scrolling css issue
_\*required_
=> Spt 7008/context bottom drawer bugfix

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tip/tip-status.enum.ts, projects/swimlane/ngx-ui/src/lib/components/tip/tip.component.html, projects/swimlane/ngx-ui/src/lib/components/tip/tip.component.scss, projects/swimlane/ngx-ui/src/lib/components/tip/tip.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/tip/tip.component.ts, projects/swimlane/ngx-ui/src/lib/components/tip/tip.module.ts, projects/swimlane/ngx-ui/src/lib/ngx-ui.module.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/components/tip-page/tip-page.component.html, src/app/components/tip-page/tip-page.component.scss, src/app/components/tip-page/tip-page.component.ts
=> Add tip component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 29.2.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/navbar/navbar.component.scss
Updates navbar background color to be solid with color supplied by UX.
_\*required_
=> Spt 7241/update navbar color

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
(release): 29.2.1
_\*required_
=> (release): 29.2.1

projects/swimlane/ngx-ui/src/public_api.ts
=> Export tip component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 29.2.2

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
(release): 29.2.3
_\*required_
=> (release): 29.2.3

projects/swimlane/ngx-ui/src/lib/components/overlay/resize-overlay.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/overlay/resize-overlay.component.ts
Added unit tests for the resize overlay component.
_\*required_
=> add unit tests for resize overlay component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 30.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 30.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 31.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 31.1.0

projects/swimlane/ngx-ui/src/lib/components/card/card-avatar/card-avatar.component.html, projects/swimlane/ngx-ui/src/lib/components/card/card-avatar/card-avatar.component.scss, projects/swimlane/ngx-ui/src/lib/components/card/card-avatar/card-avatar.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/card/card-avatar/card-avatar.component.ts, projects/swimlane/ngx-ui/src/lib/components/card/card-footer.component.html, projects/swimlane/ngx-ui/src/lib/components/card/card-footer.component.ts, projects/swimlane/ngx-ui/src/lib/components/card/card-header.component.html, projects/swimlane/ngx-ui/src/lib/components/card/card-header.component.ts, projects/swimlane/ngx-ui/src/lib/components/card/card-orientation.enum.ts, projects/swimlane/ngx-ui/src/lib/components/card/card-placeholder/card-placeholder.component.scss, projects/swimlane/ngx-ui/src/lib/components/card/card-placeholder/card-placeholder.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/card/card-placeholder/card-placeholder.component.ts, projects/swimlane/ngx-ui/src/lib/components/card/card-status.enum.ts, projects/swimlane/ngx-ui/src/lib/components/card/card.component.html, projects/swimlane/ngx-ui/src/lib/components/card/card.component.scss, projects/swimlane/ngx-ui/src/lib/components/card/card.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/card/card.component.ts, projects/swimlane/ngx-ui/src/lib/components/card/card.module.ts, projects/swimlane/ngx-ui/src/lib/components/card/card.ts, projects/swimlane/ngx-ui/src/lib/ngx-ui.module.ts, projects/swimlane/ngx-ui/src/public_api.ts, src/app/app.component.ts, src/app/app.routing.module.ts, src/app/components/card-page/card-page-routing.module.ts, src/app/components/card-page/card-page.component.html, src/app/components/card-page/card-page.component.scss, src/app/components/card-page/card-page.component.ts, src/app/components/card-page/card-page.module.ts
Figma: https://www.figma.com/file/FVaCxUjkCXhIijhndlOnGH/Orchestration-~-Build-Specifications?node-id=10810%3A219408
_\*required_
=> Add card component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 32.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/stepper/_stepper.scss, projects/swimlane/ngx-ui/src/lib/components/stepper/step.component.html, projects/swimlane/ngx-ui/src/lib/components/stepper/step.component.scss, projects/swimlane/ngx-ui/src/lib/components/stepper/step.component.ts, projects/swimlane/ngx-ui/src/lib/components/stepper/stepper.animation.ts, projects/swimlane/ngx-ui/src/lib/components/stepper/stepper.component.html, projects/swimlane/ngx-ui/src/lib/components/stepper/stepper.component.scss, projects/swimlane/ngx-ui/src/lib/components/stepper/stepper.component.ts, src/app/components/stepper-page/stepper-page.component.html, src/app/components/stepper-page/stepper-page.component.ts
- Feature(Stepper): Add `[large]` input to increase the default icon size.
- Feature(Stepper): Add `[trackBar]` input to make track bar optional.
- Feature(Stepper): Add `[progress]` input to show a progress indicator on the active step.
- Feature(Stepper): Add `[removeHighlight]` input to remove highlight color for the completed steps.
- Feature(Stepper): Add `[icon]` input to show an icon instead of the step number.
- Feature(Stepper): Add `.complete()` method to complete every step (including the last one).
_\*required_
=> Stepper customization

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 33.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 34.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.ts, src/app/components/plus-menu-page/plus-menu-page.component.html, src/app/components/plus-menu-page/plus-menu-page.component.ts
- Fix(ngx-plus-menu): classes not set correctly in some cases.
_\*required_
=> Fix plus menu class

angular.json, package-lock.json, package.json
* Bumps @angular-builders/custom-webpack to v10 (supports ng10)
* Add allowedCommonJsDependencies to angular.json
_\*required_
=> update @angular-builders/custom-webpack, add allowedCommonJsDependencies

projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts
Remove console.log from select dropdown option component
_\*required_
=> Remove console.log from select dropdown option component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/card/card-appearance.enum.ts, projects/swimlane/ngx-ui/src/lib/components/card/card.component.html, projects/swimlane/ngx-ui/src/lib/components/card/card.component.scss, projects/swimlane/ngx-ui/src/lib/components/card/card.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/card/card.component.ts, src/app/components/card-page/card-page.component.html
- Add `appearance: 'normal' | 'flat'`
- Add `hideAccent` 
- Add work-break on description 
_\*required_
=> Add appearance and hideAccent options to ngx-card

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.0.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.1.0

.gitignore, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/progress-spinner/progress-spinner.component.scss
* Make compatible with newer SCSS versions.
see https://sass-lang.com/documentation/breaking-changes/css-vars
_\*required_
=> fix spinner-color

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.1.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.1.2

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/button/file-button.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/button/file-button.component.ts, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.html, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.scss, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.ts, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.module.ts, projects/swimlane/ngx-ui/src/lib/ngx-ui.module.ts, projects/swimlane/ngx-ui/src/public_api.ts, src/app/app.component.ts, src/app/app.routing.module.ts, src/app/components/dropzone-page/dropzone-page-routing.module.ts, src/app/components/dropzone-page/dropzone-page.component.html, src/app/components/dropzone-page/dropzone-page.component.ts, src/app/components/dropzone-page/dropzone-page.module.ts
=> ngx-dropzone component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.html, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.ts, projects/swimlane/ngx-ui/src/lib/components/progress-spinner/progress-spinner.component.html, projects/swimlane/ngx-ui/src/lib/components/progress-spinner/progress-spinner.component.scss, projects/swimlane/ngx-ui/src/lib/components/progress-spinner/progress-spinner.component.ts
=> style in hostBinding compatibility issue when ivy off

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.3.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/calendar/calender.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.scss
=> Dropzone component design review

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/card/card.component.html, projects/swimlane/ngx-ui/src/lib/components/card/card.component.scss, projects/swimlane/ngx-ui/src/lib/components/card/card.component.ts, src/app/components/card-page/card-page.component.html
=> add error state to CardComponent

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.3.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
release v35.4.0 includes
- Feature(CardComponent): add error outline
- Fix(DropzoneComponent): addressing minor design review feedback
- Fix: add label color to ToggleComponent, RadioButtonComponent, CheckboxComponent
- Fix(TipComponent): change error color
- Enhancement: Add `$color-error` css var
- Feat(LargeFormatDialogContentComponent): add new component as wrapper for Dialog content
_\*required_
=> (release): 35.4.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> add missing peer dep

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.5.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.6.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.ts
=> Adjust large format dialog title

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.ts, projects/swimlane/ngx-ui/src/lib/components/drawer/dialog-drawer-content/dialog-drawer-content.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/drawer/dialog-drawer-content/dialog-drawer-content.component.ts, projects/swimlane/ngx-ui/src/lib/styles/colors/gradient-colors.scss, projects/swimlane/ngx-ui/src/lib/styles/colors/gradients.scss, projects/swimlane/ngx-ui/src/public_api.ts, src/app/dialogs/dialog-large-format-page/components/child-drawer.component.ts, src/app/dialogs/dialog-large-format-page/components/parent-drawer.component.ts, src/app/dialogs/dialog-large-format-page/dialog-large-format-dialog-page.component.html, src/app/dialogs/dialog-large-format-page/dialog-large-format-dialog-page.component.ts
=> Minor adjustments to LargeFormatDialogContent

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.6.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.ts
=> align Title when there is no subtitle

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.6.2

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.ts
=> Large format dialog header alignment

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.6.3

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release):35.6.4

projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.scss
=> Adjust Stepper content margin top in LFD

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.6.5

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.ts
=> fix: make ngx-select recalc selected options on options changes

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.6.7

src/app/forms/datetime-page/datetime-page.component.html
=> uncomment the demo page

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 35.9.0

cypress/integration/components/tabs.spec.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tabs/tab.component.ts, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.html, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.scss, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.ts, src/app/components/tabs-page/tabs-page.component.html
- Breaking: Improve semantic HTML in `ngx-tabs` (now not using `li`)
- Enhancement: Added ARIA role attribute to `ngx-tabs`
- Feature: Added focus rings to `ngx-tabs` buttons
_\*required_
=> a11y for tabs

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.html, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.scss, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.ts, src/app/components/tabs-page/tabs-page.component.html
* Added styles for vertical alignment
_\*required_
=> Add vertical alignment for `ngx-tabs`

projects/swimlane/ngx-ui/src/lib/components/input/input.component.spec.ts
=> remove fit

package-lock.json, package.json, projects/swimlane/ngx-ui-testing/package.json, projects/swimlane/ngx-ui-testing/src/commands.d.ts, projects/swimlane/ngx-ui-testing/src/commands.ts, projects/swimlane/ngx-ui-testing/src/functions.ts, projects/swimlane/ngx-ui-testing/src/overrides.ts, projects/swimlane/ngx-ui-testing/tsconfig.json
* Updates for Cypress v9
* Beta version
_\*required_
=> Updates to ngx-ui-testing

src/app/forms/datetime-page/datetime-page.component.html, src/app/forms/inputs-page/inputs-page.component.html, src/app/forms/inputs-page/inputs-page.component.ts, src/app/forms/selects-page/selects-page.component.html, src/styles.scss
=> add demo for various appearances and states

src/app/dialogs/tooltip-page/tooltip-page.component.html
=> Changed tooltip hrefs to anchors

cypress/integration/forms/inputs.spec.ts
* Fix failing input test
_\*required_
=> fix input test

cypress/integration/forms/checkbox.spec.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.html, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.scss, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.ts, src/app/forms/checkbox-page/checkbox-page.component.html, src/app/forms/checkbox-page/checkbox-page.component.ts, src/app/forms/checkbox-page/checkbox-page.module.ts
* add `checked` and `checkedChange` to checkbox
* Add cypress-axe to evaluate WCAG level A
* keyboard accessible/tab order
_\*required_
=> Feature: add `checked` input to checkbox

cypress/integration/forms/date-inputs.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, src/app/forms/datetime-page/datetime-page.component.html, src/app/forms/datetime-page/datetime-page.component.ts
* Fix issues where dates were not emitted correctly
_\*required_
=> More date time fixes!!

README.md, cypress/integration/components/calendar.spec.ts, projects/swimlane/ngx-ui/CHANGELOG.md
Fixing cypress test for calendar
Adding additional steps and information for the installation process.
_\*required_
=> Fixing cypress test and modifying installation steps in Readme file

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Adding additional steps and information for the installation process.
_\*required_
=> Release 37.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 38.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/button/button.component.html, projects/swimlane/ngx-ui/src/lib/components/button/button.component.scss, projects/swimlane/ngx-ui/src/lib/styles/components/buttons.scss, src/app/forms/buttons-page/buttons-page.component.html, src/app/forms/buttons-page/buttons-page.component.scss, src/app/forms/buttons-page/buttons-page.component.ts
* Fix hover state
* Fix success and failed states for primary gradient
* Removed border for success and failed states
_\*required_
=> consistent button states

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/contains-filter.util.spec.ts, projects/swimlane/ngx-ui/src/lib/components/select/contains-filter.util.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.spec.ts, projects/swimlane/ngx-ui/src/lib/utils/regex/escape.util.spec.ts, projects/swimlane/ngx-ui/src/lib/utils/regex/escape.util.ts
- Escape special character on select filter regex
_\*required_
=> SPT-11619: RegExp Injection

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 38.1.0

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-types.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.extensions.scss, src/app/components/card-page/card-page.component.scss, src/app/components/json-editor-page/json-editor-page.component.html, src/app/components/json-editor-page/json-editor-page.component.ts
Old design
New Design
_\*required_
=> Update json flat editor component designs in ngx UI

angular.json
Added the following config to angular.json so that sourcemaps are enabled to enable debugging
```
"preserveSymlinks": true,
```
and
```
"sourceMap": {
"scripts": true,
"styles": true,
"vendor": true
}
```
_\*required_
=> Allow debugging in dev mode

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss
=> add margin bottom to tags

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-types.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.ts
Fix some issues on the json editor
Fix: Add an array inside an array in json editor works
Fix: Adding a code , date , date-time or password inside an Array in the json Editor works
_\*required_
=> Fix styles and bugs on json-editor-flat

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.html, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.scss, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.component.ts, projects/swimlane/ngx-ui/src/lib/components/dropzone/dropzone.module.ts, src/app/components/dropzone-page/dropzone-page.component.html
=> Dropzone small

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 40.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 40.1.0

projects/swimlane/ngx-ui/CHANGELOG.md
=> Cleanup change log, add a11y tags

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss, src/app/forms/selects-page/selects-page.component.html, src/app/forms/selects-page/selects-page.component.ts, src/styles.scss
Fix some select overflow issues
_\*required_
Before:
After:
=> Select overflow

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Bumping to 40.3.0
_\*required_
=> (release): 40.3.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Bumping version to 40.4.0
_\*required_
=> (release): 40.4.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss
=> fix tagging size issue

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> Revert "(release): 40.5.1"

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 42.0.4

package-lock.json
=> Chore: update caniuse

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-types.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/property-config/property-config.component.ts
- Fix issue with indent when `hideRoot = false`
- Fix issue with missing `required` array.
_\*required_
=> More json editor fixes

package-lock.json, package.json, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.ts
=> bump rxjs in demo, update peer dep

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 42.0.7

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 42.0.8

cypress/e2e/components/json-editor.cy.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/object-node.component.ts
Before:
https://user-images.githubusercontent.com/62297014/178605572-5a6d5f7d-6675-44db-b03f-998531f18282.mov
After:
https://user-images.githubusercontent.com/62297014/178605826-239d843d-21c8-4417-955d-28b5a3f67683.mov
_\*required_
=> Bug fix json editor flat

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/button/button.component.scss
=> fix clipping issue on buttons

package-lock.json, package.json
Remove @ngneat/spectator (not used)
_\*required_
=> remove unused dep

package-lock.json, package.json, projects/swimlane/ngx-ui/CHANGELOG.md
Upgrading to Cypress 10.6.0.
_\*required_
=> Initial upgrade Cypress v10

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 42.2.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 42.3.1

cypress/e2e/dialogs/medium-format-dialog.cy.ts, projects/swimlane/ngx-ui-testing/src/commands.ts, projects/swimlane/ngx-ui-testing/src/functions.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog-format.enum.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.component.html, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-footer/large-format-dialog-footer.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-footer/large-format-dialog-footer.component.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content-drawer.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.html, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.ts, src/app/app.component.ts, src/app/app.routing.module.ts, src/app/dialogs/dialog-medium-format-page/dialog-medium-format-dialog-page.component.html, src/app/dialogs/dialog-medium-format-page/dialog-medium-format-dialog-page.component.scss, src/app/dialogs/dialog-medium-format-page/dialog-medium-format-dialog-page.component.ts, src/app/dialogs/dialog-medium-format-page/dialog-medium-format-page-routing.module.ts, src/app/dialogs/dialog-medium-format-page/dialog-medium-format-page.module.ts
Add medium format dialog
_\*required_
=> Add Medium sized variant of large format dialog

projects/swimlane/ngx-ui-testing/package.json, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 42.4.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
[SPT: 14582 update integer playbook input
](https://github.com/swimlane/ngx-ui/pull/946)
~- [ ] \*Added unit tests~
~- [ ] Updated the demo page~
_\*required_
=> (release): 42.6.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 43.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.0.0

projects/swimlane/ngx-ui/package.json
Removed outdated maintainers information from package.json
_\*required_
=> remove maintainers array from package.json

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.2.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.3.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.3.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.4.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.5.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.5.2

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts
Fixed the focus issue of dropdown items:
**Before**
**After**
_\*required_
=> fix focus issue of dropdown items

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.5.3

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.5.4

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 44.6.0

projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.component.scss
Updates base dialog text color
_\*required_
=> Update base dialog text color

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/card/card.component.scss
Update ngx-ui card component: 
- Background change from gradient to solid. 
- Removing left border from NGX section from the component.
Before
After
_\*required_
=> SPT-19835: Changing card style

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 45.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 45.0.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 45.0.2

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 45.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Release PR for 45.1.1.
_\*required_
=> (release): 45.1.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/split/split.directive.spec.ts, projects/swimlane/ngx-ui/src/lib/components/split/split.directive.ts, src/app/components/split-page/split-page.component.html, src/app/components/split-page/split-page.component.ts
=> (release): 47.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar-select.enum.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.html, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.scss, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.module.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calender.component.spec.ts, src/app/forms/calendar-page/calendar-page.component.html, src/app/forms/calendar-page/calendar-page.component.ts
=> Range selection in calendar v46

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar-select.enum.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.html, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.scss, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.module.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calender.component.spec.ts, src/app/forms/calendar-page/calendar-page.component.html, src/app/forms/calendar-page/calendar-page.component.ts
=> Range selection in calendar

angular.json, package.json, projects/swimlane/ngx-ui-testing/ng-package.json, projects/swimlane/ngx-ui-testing/package.json, projects/swimlane/ngx-ui/CHANGELOG.md
- Breaking: Angular 18 support
- Breaking: ngx-ui-testing package `iff` method may behave differently given `within` call is move internally
- Enhancement (`ngx-radiobutton`): Added `toggle` method to align with ngx-checkbox and ngx-toggle
There were also some changes necessary to package @swimlane/ngx-ui-testing.
_\*required_
=> (release): 48.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
- Enhancement: Provide normalize css internally to support esbuild.
_\*required_
=> (release): 48.0.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 48.0.2

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 48.0.3

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 48.0.4

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.html, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calender.component.spec.ts
* feat: validation for time in date range selection
* fix: possible bug when selecting am / pm could produce incorrect time
* fix: date range selection should be accurate when selecting am/pm
This PR makes several improvements to date range selection.
_\*required_
=> Calendar Date Range Selection

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 48.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Release PR for version 49.1.0.
_\*required_
=> Release 49.1.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> Release 49.2.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 49.2.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 50.0.0-alpha.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> (release): 50.0.0-alpha.2

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/styles/colors/_vars.scss, projects/swimlane/ngx-ui/src/lib/styles/index.scss, projects/swimlane/ngx-ui/src/lib/styles/layouts/_vars.scss, projects/swimlane/ngx-ui/src/lib/styles/typography/_vars.scss, projects/swimlane/ngx-ui/src/lib/styles/variables.scss
This PR adds new CSS variable definitions for colors, layouts, and typography to the codebase.
The variables are organized into separate files.
This adds support for CSS variables to support styling of Components with browser standards and values direct from Swimlane design system.
=> feature: CSS variables

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Fix (`ngx-column`): Content should display when column child is active on load.
_\*required_
=> (release): 50.0.0-alpha.5

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.html, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.scss, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.ts, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/models/date-range.model.ts, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/services/date-utils.service.ts, projects/swimlane/ngx-ui/src/lib/components/filter/filter.component.html, projects/swimlane/ngx-ui/src/lib/components/filter/filter.component.ts
Integrated tooltip support within the Date Range Picker component.
Enabled tooltip customization for filters by accepting a tooltip template as an input.
https://github.com/user-attachments/assets/5cd2e952-2ee0-401d-bad8-91ef1246b36f
_\*required_
=> tooltip added for date range component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
* Enhancement (ngx-filter): Added new inputs to show tooltip for customDropdown
* Enhancement (ngx-date-range-picker): Added tooltip
* Enhancement (ngx-date-range-picker): Added future preset values
* Enhancement (ngx-date-range-picker): Input Fields for preset values display relative expressions (e.g., now-2d to now) instead of converted date values for better clarity and editing.
* Enhancement (ngx-column): Added output onColumnChange that emits an event whenever the user changes the active column.
_\*required_
=> (release): 50.0.0-alpha.6

projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.ts
Added tooltip for preset values
https://github.com/user-attachments/assets/f3714003-13f3-4f54-bfc0-68ddb0f6899d
_\*required_
=> tooltip for presets in date range component fix

projects/swimlane/ngx-ui/CHANGELOG.md
Updated change log for tooltip
_\*required_
=> update change log

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.scss, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.ts
tooltip added for the selectedRange input values
tooltip css corrected
https://github.com/user-attachments/assets/44c6a81d-e5c9-46fa-8762-e6904d58108d
_\*required_
=> Date range tooltip fix

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> Release 50.0.1

projects/swimlane/ngx-ui/ng-package.json, projects/swimlane/ngx-ui/package.json
Added date-fns to project dependencies
_\*required_
=> Added date-fns to project dependencies

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> Release 50.0.3

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
=> Release 50.1.2
