swimlane/ngx-ui

config/webpack.dev.js
=> (fix) remove poller from webpack-dev-server watch options

demo/app/app.template.html, src/components/dropdown/dropdown.component.ts
Adds a `closeOnOutsideClick` input to the dropdown component, which when set to false prevents the dropdown from being closed by clicking outside of it.
This was needed because when adding a date input or a select input inside a dropdown, selecting a value in them would close the dropdown too.
=> (feat): Add closeOnOutsideClick input to dropdowns

CHANGELOG.md, src/components/button/file-button.component.scss, src/components/button/file-button.component.ts
ngx-file-upload will wrap `<input type="file">` elements in a `<div>` rather than a `<button>` (the latter of which is not supported in non-Chrome browsers). Tested in Firefox and Chrome.
=> ngx-file-upload non-Chrome browser support

CHANGELOG.md, src/components/dialog/dialog.component.scss, src/styles/components/buttons.scss
Fixes the dialog close button being invisible and sets the font weight of ngx-icons inside of buttons to "normal."
=> Minor Styling Fixes

CHANGELOG.md, src/components/dialog/dialog.component.scss
Puts the dialog close button back where it belongs.
=> Dialog Close Button Fix

projects/swimlane/ngx-ui/src/lib/components/icon/icon.module.ts, src/app/app.module.ts
Removes the HttpClientModule from IconModule. See https://github.com/angular/angular/issues/20575 for details.
=> Remove HttpClientModule from IconModule

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Sets `sideEffects` to `[*.css]` in package.json.
This field is used by module bundlers like Webpack to determine which files in a library are tree shakable. By default, the Angular CLI sets this field to `false` when building a library, which indicates to Webpack that all files in the library are tree shakable when Webpack's `optimization.sideEffects` flag is set to `true` or when the `SideEffectsFlagPlugin` is used, which is the default configuration when Webpack's `mode` is set to `'production'`. See [here](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) for more info about how Webpack uses the `sideEffects` field.
In cases where a consumer loads `ngx-ui/index.css`, it's not safe for Webpack or other module bundlers to attempt to tree shake the file, and …
=> Mark *.css in pkg.sideEffects

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/styles/components/buttons.scss
Fixes weird inner-background on `button` elements inside an `.ngx-button`:
=> ngx-button Background Fix

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.ts
`(select)` event is emitted when text is selected within an element.  Added `selectTab` to avoid this.
=> ngx-tabs now have a (selectTab) output to avoid conflict with (select)

projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.ts
Template now renders correctly when types are not initially defined. Items in the array also no longer default to the Object icon if the type can be inferred.
=> Initialize schema types for arrays in json-editor

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts
- Fix: `ngx-date-time` picker should emit `(ngModelChange)` on change instead of on blur by default
- Fix: `ngx-date-time` should default to correct format
- Feature: `ngx-date-time` respects `ngModelOptions`
=> Fix ngx-date-time issues

projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts
When model was inside an array `[ngModel]="[someVar]"` the invalid class was not triggered if `someVar === undefined || null || "" `
=> ngx-select required validation fix

projects/swimlane/ngx-ui/src/lib/components/hotkeys/hotkeys.service.ts, src/app/components/hotkeys-page/hotkeys-page.component.html
By default, Mousetrap disables keyboard events when the focus is on an input, textarea or select element. We can now pass an optional `allowIn` property to the hotkey definition to override this behavior.
=> Support allowIn in hotkeys

projects/swimlane/ngx-ui/src/lib/components/code-editor/mustache.ts, src/app/app.component.scss, src/app/app.component.ts, src/app/app.template.html
This PR adds a search box to the top of the sidebar, under the ngx-ui logo. It filters live as the user types, dynamically updating the list of components shown in the sidebar.
=> Add ability to search for specific components from the sidebar.

projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.ts
Addresses an issue where tabs component is throwing a `Expression has changed after it was checked` error after upgrading to Ivy.
=> Fix changed after check error

projects/swimlane/ngx-ui/src/lib/components/hotkeys/hotkeys.service.ts
Summary:
- on component destroy, hotkey deregister service used by service and decorator is not removing callback bind
Fix:
- fix bad for loop so deregister works
=> fix bugged for look that failed to manipulate array properly

projects/swimlane/ngx-ui/src/lib/components/toolbar/toolbar.component.html
Since there is now a default value for `menu`, do a length check on the menu array to determine whether to render the array values or `ngx-toolbar-content` if menu items are absent
=> do length check on toolbar menu items

projects/swimlane/ngx-ui/src/lib/directives/directives.module.ts
Getting this error while doing `ng serve`: 
``` ERROR in Unexpected value 'undefined' imported by the module 'ɵbb in /Users/duredhel/Documents/Swimlane/turbine/packages/turbine-ui/node_modules/@swimlane/ngx-ui/swimlane-ngx-ui.d.ts' ```
This fixes that issue.
=> Refactor PatternValidatorModule  to fix import

projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.html, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.ts, src/app/forms/toggle-page/toggle-page.component.html
Summary:
- @luisb90 pointed out ngModelChange firing multiple times per change
- fix duplicate change calls
- fix demo page component usage
=> Breaking: fix toggle ng model change

projects/swimlane/ngx-ui/src/lib/components/tree/fixtures/tree.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/tree/tree-node.component.html, projects/swimlane/ngx-ui/src/lib/components/tree/tree-node.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/tree/tree-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/tree/tree-node.model.ts, projects/swimlane/ngx-ui/src/lib/components/tree/tree.component.html
It seems `selectable` and `disabled` are not configurable for ngx-tree when no templates are used.
As a result it's not possible to disable or make anything selectable with the stock configuration of ngx tree.
In addition I've added `selectNode` to the nested trees in order for that event to 'bubble' up and I'm canceling propagation when a node is expanded otherwise an expand will also trigger a select which seems undesirable.
This pr purposes a suggested change and does not have to be merged perse.
=> Add selectable and disabled to tree node model

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, src/app/components/json-editor-page/json-editor-page.component.html, src/app/components/json-editor-page/json-editor-page.component.ts
Expose a schema update when model changes, without modifying the original schema.
Updates on add property are already on master. This PR fixes the delete property.
=> Export schema on model update

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-types.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor.component.scss
Add the ability to hide the root note on the json editor flat component.
Usage:
`<ngx-json-editor-flat [hideRoot]="true" ... ></ngx-json-editor-flat>`
=> json editor hide root node

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tree/tree-node.component.html, projects/swimlane/ngx-ui/src/lib/components/tree/tree-node.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/tree/tree-node.component.ts, src/app/components/tree-page/tree-page.component.html, src/app/components/tree-page/tree-page.component.ts
* Moved click event on node to avoid using stop propagation in click event.
=> Move click event on tree nodes to avoid propagation

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.ts
Ensure that the properties order is not affected after renaming a prop.
=> JSON Editor Schema Output bug

projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts
There is an issue where ngx-select never turns red when required and touched. This PR fixes that problem.
=> Fix ngx-select setting invalid class when touched.

projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts
Currently tab fails on a form for ngx-select. They will just skip that input. This PR fixes that and also allow the user to open the dropdown with the down arrow key making it close to a common HTML select behavior.
=> Support tabindex on select inputs

projects/swimlane/ngx-ui/src/lib/components/tooltip/tooltip.directive.ts
Fixes two issues:
1) If the mouse leaves the tooltip source element to the tooltip content, then returns to the original source the mouse leave event was fired, closing the tooltip.
2) Sometimes when the tooltip content is bein rendered in the DOM, before being pleaced in the correct position, it will be located over the tooltip source element... triggering #1.
Now if the mouse leaves the tooltip content but the target is the source element, the tooltip is not closed.
=> Fix mouse leave firing if returning to source

projects/swimlane/ngx-ui/src/public_api.ts
export deps required by platform so we can bump version.
=> SPT-6292/export-missing-deps

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, src/app/components/json-editor-page/json-editor-page.component.html, src/app/components/json-editor-page/json-editor-page.component.ts
- Feature: support dynamic `hideRoot` inputs
- Fix: required icon not showing for top level when `hideRoot` is true
_\*required_
=> Fix required icon missing when hideRoot is true

projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss
When using the `allowAdditions` property on the select component, when the filter query string matches one of the options, the user has no way of adding a new value until the filterQuery does not match any of the options. At that point the `add new value` element is available and a new value can be added. This fix introduces the possibility to the user of adding a new value even when the filterQuery matches at least one option.
Before:
After:
_\*required_
=> Allow add new value on selects when filter query matches some options

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/overlay/resize-overlay.component.html, projects/swimlane/ngx-ui/src/lib/components/overlay/resize-overlay.component.scss
Fix resize overlay leak css
_\*required_
=> fix resize overlay leak css

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/styles/fonts/source-sans.scss, scripts/prep-global-styles.js
- Ensure text remains visible during webfont load (https://web.dev/font-display/?utm_source=lighthouse&utm_medium=devtools)
_\*required_
=> Source Sans Pro fonts now defined with `font-display: swap` for better UX

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-types.extensions.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-node.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.module.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/array-node/array-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/object-node/object-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/object-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/tooltip/tooltip.component.scss, src/app/components/json-editor-page/json-editor-page.component.html, src/app/components/json-editor-page/json-editor-page.component.ts
- Added option to show all properties on an object
- Shows placeholder for optionl properties defined in schema but not in model
- Hides new property and when show all properties and additionalProperties is false
- Hide known properties column in dropdown when `showAllObjectProperties` is true
- click on whole node to add property
- known properties say remove instead of delete in action dropdown
- in both compressed and expanded views node height is fixed.
https://www.screencast.com/t/nAK68ntEEY
_\*required_
=> show all properties option

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/stepper/step.component.scss, projects/swimlane/ngx-ui/src/lib/components/stepper/stepper.component.scss, src/app/components/stepper-page/stepper-page.component.html
- Show stepper labels for horizontal stepper
_\*required_
=> Show stepper labels for horizontal stepper

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/input/input-animations.constant.ts, projects/swimlane/ngx-ui/src/lib/components/input/input-autosave.directive.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/input/input-autosize.directive.spec.ts, projects/swimlane/ngx-ui/src/lib/components/input/input-autosize.directive.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.html, projects/swimlane/ngx-ui/src/lib/components/input/input.component.scss, projects/swimlane/ngx-ui/src/lib/components/input/input.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.ts, projects/swimlane/ngx-ui/src/lib/mixins/appearance/appearance.enum.ts, projects/swimlane/ngx-ui/src/lib/mixins/appearance/appearance.mixin.ts, projects/swimlane/ngx-ui/src/lib/mixins/constructor.type.ts, projects/swimlane/ngx-ui/src/lib/mixins/size/size.enum.ts, projects/swimlane/ngx-ui/src/lib/mixins/size/size.mixin.ts, src/app/forms/inputs-page/inputs-page.component.html
- add reusable mixins for appearance and size (links to other impl examples in commit descriptions)
- enhance autosize directive to work with input (width) as well as textarea (height)
- add input for autosize that enables input resize when type is not textarea
- add fill styles
- add sizing styles (sm, md, lg)
- update all other input styles to match figma
- update unit tests
_\*required_
=> SPT-6965/fill-input

projects/swimlane/ngx-ui/src/lib/components/split/split-area.directive.ts
Add max min width conditional control to ngx-split-area directive.
_\*required_
=> Add max min width conditional control to ngx-split-area directive

projects/swimlane/ngx-ui/src/lib/components/input/input-autosize.directive.spec.ts
- use empty string for no scroll tests, faker words are random and could exceed width/height sometimes.
_\*required_
=> don't use faker for no-scroll test because words may be too long

projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.spec.ts
Only display the Add Value `<li>` when the `allowAdditions` flag is set to true. Currently, when a user is filtering and the `allowAdditions` flag is false, the `<li>` is still being added with nothing inside it. 
Before:
After:
_\*required_
=> Only add add value li when allow additions is set to true

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select.component.fixture.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss, projects/swimlane/ngx-ui/src/lib/components/select/select.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts, src/app/forms/selects-page/selects-page.component.html
Updated the select component to include a "fill" appearance variant, as shown in the screenshot. This also included an updating of the dropdown styling that applies to both the fill and legacy variants, based on latest designs from UX. For the fill variant, the select will automatically fit to its contents up to the max width of its parent container. If no choice is selected, the select will initialize to the width of either the placeholder or the label if defined.
_\*required_
=> SPT-6967 - select input fill variant

projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts
Adding the check back to be a match rather than partial. Looking back into it, what we are checking there is if the filterQuery exactly matches one of the options, we want the add value button to be removed since it is available as an option and we don't want to add a new value with the exact same name(which might cause bugs as well). If we have partial matches, we do want the add value button displayed, to enable the user to add a new value.
_\*required_
=> Update UpdateFilterQueryIsInOptions method

projects/swimlane/ngx-ui/src/lib/components/button/button.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/button/button.component.ts
The promise input on the ngx-button had a bug where responses of promises that took longer than 3 seconds, would correctly go into `inProgress` state, then into active state after 3 sec and then properly update the state (success, fail) rather than remaining in the `inProgress` state until the promise resolved/rejected. This was happening because inside the `updatePromise` method, the `updateState` method was being called, which would set the state to `active` after the timer would end, which is set to 3 seconds. Removing this call allows the state to remain `inProgress` up until the Promise is resolved/rejected, which is the desired behavior. This wasn't happening in promises in that took less than 3 seconds to resolve/reject because the timer would be cleared in time before changing …
=> Promise button bug fix

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts
- Fixed ngx-select caret so that it properly toggles the dropdown. 
- Made the entire input box a toggle, as before it only opened the dropdown.
- Updated the border on the ngx-select to remove the chrome accessibility outline and use our underline on focus
_\*required_
=> update ngx-select component to fix focus underline and caret bug

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.html, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.scss, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.html, projects/swimlane/ngx-ui/src/lib/components/input/input.component.scss, projects/swimlane/ngx-ui/src/lib/components/input/input.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts, src/app/forms/datetime-page/datetime-page.component.html, src/app/forms/inputs-page/inputs-page.component.html
Updated the `ngx-date-time` component to have a fill appearance variant and support autosizing.
as part of this, also fixed the following bugs I found in ngx-input:
- when autosize is set with an initial value, the component will now properly autosize to that value on init
- The numeric spinners now emit a change event on press
_\*required_
=> Spt-7598 - datetime fill autosize

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/styles/components/datatable.scss, projects/swimlane/ngx-ui/src/lib/styles/components/index.scss, projects/swimlane/ngx-ui/src/lib/styles/index.scss
Platform and Turbine use ngx-datatble stylesheet so reverting the change that was made recently.
_\*required_
=> bring back ngx-datatable style

angular.json, cypress/integration/forms/selects-spec.js, cypress/support/commands.js, cypress/support/index.d.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts, src/app/forms/selects-page/selects-page.component.html
- Make span.ngx-select-caret a sibling to div.ngx-select-input-box
instead of a child. This removes the need for event.stopPropagation
which cancels all click listener on the document.body (for
closeOnBodyClick)
- Add Cypress test for "close on body click" cases
- Have not added tests for cases with closeOnBodyClick set to `false`
- Some imports reformating
_\*required_
=> fix: select not auto-collapse when click on caret

projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts
Display value for `<ngx-date-time />` not updated when used as part of a reactive form. Steps to reproduce:
```html
<div [formGroup]="form">
<ngx-date-time formControlName="date"> </ngx-date-time>
</div>
```
After selecting the date and clicking the `Apply` button the input field is not updated.
_\*required_
=> Fix displayValue for DateTimeComponent

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar-day.interface.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/utils/get-days-for-month/get-days-for-month.util.ts, projects/swimlane/ngx-ui/src/lib/components/hotkeys/hotkeys.service.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/schema-validator.service.ts, projects/swimlane/ngx-ui/src/lib/components/notification/notification.mock.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown-option.mock.ts
Some Jest tests were failing with the latest library version on ng10. Still not sure why, but fixing the imports also fixes the tests. 
_\*required_
=> fix: change * imports to a namespaces compatible version

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/array-node/array-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/array-node/array-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/object-node/object-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/object-node/object-node.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/object-node/object-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/object-node.component.ts
When a property's name is duplicated in an `object-node` both properties are assigned with the same ref causing unexpected behaviors.
This PR provides a protection against property name duplication and visual warning.
_\*required_
=> fix: json editor prop duplication

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/object-node.component.ts
The `object-node.component` is not re-inferring the properties type after the model input change
_\*required_
=> fix: recalculate node type on model change

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.html, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, src/app/forms/datetime-page/datetime-page.component.html
- Enhancement: Add `required` and `requiredIndicator` inputs to `DateTimeComponent`.
- Breaking: An empty value will no longer cause the `DateTimeComponent` to become invalid, unless it is explicitly marked as `required`.
_\*required_
=> Add 'required' input to DateTimeComponent

projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.module.ts, src/app/forms/selects-page/selects-page.component.html
Add ability to use custom template for `group` when `groupBy` is on.
normal:
with custom template:
_\*required_
=> feat: add custom template to group on select with groupBy

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.html, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.scss, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.ts, src/app/components/plus-menu-page/plus-menu-page.component.html, src/app/components/plus-menu-page/plus-menu-page.component.ts
Breaking:
To support multiple plus-menu instances on a single page:
- `ngx-plus-menu` takes items containing `title` and `subtitle` instead of `description` and `hotkeys`. 
- Does not setup it's own hotkeys.
Bugfix:
- no popup us shown if `menuTitle` is not passed as an input to `ngx-plus-menu`
_\*required_
=> changes to plus menu

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts
- Fix(DateTime): Component no longer emits a `(change)` event when input value is invalid.
- Fix(DateTime): Display value not updated correctly when input cleared.
_\*required_
=> Fix: datetime displayValue

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.html, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, src/app/forms/datetime-page/datetime-page.component.html, src/app/forms/datetime-page/datetime-page.component.ts
Add `blur` and `dateTimeSelected` outputs to DateTimeComponent
_\*required_
=> Add blur and dateTimeSelected outputs to dateTimeComponent

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.helper.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.html
JSON Editor should handle 'null' property type. See: https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.1
_\*required_
=> Allow 'null' as a valid schema type

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.html, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.scss, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.ts, src/app/forms/toggle-page/toggle-page.component.html
Enhancement: Add `showIcons` input to `ToggleComponent`  in order to display the optional icons.
Default value is set to true. But you can turn it off anytime you want.
_\*required_
=> Add 'showIcons' input to ToggleComponent

package-lock.json, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts
Add `inputChange` output for `ngx-date-time` to emit input changes even if the input value is not a valid date
In certain cases, it's helpful to have an event that the value has changed, for example to run side effects in a [Component Store](https://ngrx.io/guide/component-store). even when a value isn't valid for for the desired Date/Datetime format.
This does not change the control value logic already in place, where it would only update the value if it valid or cleared. 
_\*required_
=> Add extra @Output() for Date Picker to always emit value change

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/button/button.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/button/button.component.ts, src/app/forms/buttons-page/buttons-page.component.html
- When `timeout` is 0, do not add the timeout
- When `timeout` is undefined, default to 3000ms
_\*required_
=> Add timeout option to ngx-button

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/input/input.component.scss
Make clickable the lockpad icon that appears when a textbox has `[unlockable]="true"` set. This was not functional when using the fill appearance. Also, fixes vertical alignment.
Closes #552
_\*required_
=> Make lockpad icon clickable when textbox is unlockable and appearance is set to fill

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.html, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.scss, projects/swimlane/ngx-ui/src/lib/components/plus-menu/plus-menu.component.ts, src/app/components/plus-menu-page/plus-menu-page.component.html, src/app/components/plus-menu-page/plus-menu-page.component.ts
A little hacky, but we needed a way to apply gradient on the svg for a seamless color transition.
_\*required_
=> Add a custom color option for ngx-plus-menu items

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/card/card.component.ts, projects/swimlane/ngx-ui/src/lib/components/section/section.component.ts, src/app/components/card-page/card-page.component.html
HostBinding wipes out other class definitions when Ivy is off:
_\*required_
=> Fix hostbinding issue

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/section/section-toggle-position.enum.ts, projects/swimlane/ngx-ui/src/lib/components/section/section.component.html, projects/swimlane/ngx-ui/src/lib/components/section/section.component.scss, projects/swimlane/ngx-ui/src/lib/components/section/section.component.ts, src/app/components/sections-page/sections-page.component.html
- Bug(ngx-section): Make toggle on header click optional
- Feature(ngx-section): Add `None` toggle position
_\*required_
=> fix collapse, add toogle position none

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/alert/alert.service.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.module.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/dialog.service.ts, projects/swimlane/ngx-ui/src/lib/components/drawer/drawer.module.ts, projects/swimlane/ngx-ui/src/lib/components/drawer/drawer.service.ts, projects/swimlane/ngx-ui/src/lib/components/hotkeys/hotkeys.module.ts, projects/swimlane/ngx-ui/src/lib/components/hotkeys/hotkeys.service.ts, projects/swimlane/ngx-ui/src/lib/components/icon/icon.module.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.module.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/schema-validator.service.ts, projects/swimlane/ngx-ui/src/lib/components/loading/loading.module.ts, projects/swimlane/ngx-ui/src/lib/components/loading/loading.service.ts, projects/swimlane/ngx-ui/src/lib/components/notification/notification.module.ts, projects/swimlane/ngx-ui/src/lib/components/notification/notification.service.ts, projects/swimlane/ngx-ui/src/lib/components/overlay/overlay.module.ts, projects/swimlane/ngx-ui/src/lib/components/overlay/overlay.service.ts, projects/swimlane/ngx-ui/src/lib/components/tooltip/tooltip.module.ts, projects/swimlane/ngx-ui/src/lib/components/tooltip/tooltip.service.ts, projects/swimlane/ngx-ui/src/lib/ngx-ui.module.ts, projects/swimlane/ngx-ui/src/lib/services/icon-registry/icon-registry.service.ts
Provide singleton services in the root injector.
When singleton services that manage some sort of internal state are added to the module providers list vs the root injector, we can end up with multiple instances of the service (in lazy loaded modules, for example) resulting in an incorrect behavior.
The `DialogService` holds a collection of all the open dialogs (actually the collection is inherited from the abstract base class `InjectionRegistryService<T>`). The `destroyAll()` method iterates the collection and destroys all dialogs. Obviously having multiple instances of this particular service could be problematic:
```ts
// ...
dialogService__A.create({ /* ... */ });
dialogService__B.destroyAll(); // B's collection is empty, nothing to destroy here!
```
_\*required_
=> Provide services in root injector

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts
Add validation when change on minDate or maxDate occurs.
In this particular example we are using the value of the first component to be the value for the `[minDate]` input on the second component. 
When the first component value is changed, then the error message on the second component should go away, because now it is a valid date. 
That behavior was missing, because we did not have any validation happening after any change on the `minDate` or `maxDate`, the error message was always displayed, even if it was a valid date after the `minDate` value was changed.
_\*required_
=> Add validation when change on minDate or maxDate occurs

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts, src/app/forms/selects-page/selects-page.component.html
Add ability to add new values to select via shift + enter
_\*required_
=> Add ability to add additions via shift + enter with select

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tip/tip-status.enum.ts, projects/swimlane/ngx-ui/src/lib/components/tip/tip.component.scss, projects/swimlane/ngx-ui/src/lib/components/tip/tip.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/tip/tip.component.ts, src/app/components/tip-page/tip-page.component.html, src/app/components/tip-page/tip-page.component.ts
- Add `Warning Status` to Tip Component
- Add ability to display a custom icon
- Updated demo page to display these two new enhancements
_\*required_
=> Add warning status to tip component, add ability to display a custom icon

cypress/integration/components/dropdowns.spec.ts, cypress/integration/forms/selects.spec.ts, cypress/integration/testing.spec.ts, projects/swimlane/ngx-ui-testing/README.md, projects/swimlane/ngx-ui-testing/package.json, projects/swimlane/ngx-ui-testing/src/commands.ts, projects/swimlane/ngx-ui-testing/src/functions.ts, projects/swimlane/ngx-ui-testing/src/overrides.ts, src/app/app.routing.module.ts, src/app/testing-page/testing-page.component.html, src/app/testing-page/testing-page.component.ts, src/app/testing-page/testing-page.module.ts
* more logging to ngx-ui-testing
* support `cy.select` on dropdowns
* support `cy.select` on selects using templates
* respect `withinSubject` when using `getByLabel`
* published ngx-ui-testing v1.1.1
_\*required_
=> Ngx testing iv

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.scss
When the toggle is disabled it overflows to the left side of the component. Not by much, but when the parent has an `overflow: hidden` then the cropped circle is very noticeable.
**Before**
**After**
_\*required_
=> fix(ngx-toggle): toggle going out of bounds when disabled

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.html
Tabs in `ngx-tabs` are now `type="button"`
_\*required_
=> fix tab buttons (fixes #661)

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.scss, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/array-node/array-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/array-node/array-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/object-node/object-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/node-types/object-node/object-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor.component.ts, src/app/components/json-editor-page/json-editor-page.component.html, src/app/components/json-editor-page/json-editor-page.component.ts
=> fix(json-editor): use password type for password fields

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.scss
Improve active tab contrast in `ngx-tabs`
_\*required_
Was:
Now:
=> Improve active tab contrast (fixes #659)

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.ts
- added `forceDownwardOpening` input to `ngx-dropdown`
- set default `forceDownwardOpening` on `ngx-dropdown` to false until #690 
_\*required_
=> force dropdowns down for now

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs-appearance.enum.ts, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.scss, projects/swimlane/ngx-ui/src/lib/components/tabs/tabs.component.ts, src/app/components/tabs-page/tabs-page.component.html
* Added 'light' appearance to `ngx-tabs`
_\*required_
=> Added 'light' appearance to `ngx-tabs`

cypress/integration/components/sections.spec.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/section/section-appearance.enum.ts, projects/swimlane/ngx-ui/src/lib/components/section/section.component.html, projects/swimlane/ngx-ui/src/lib/components/section/section.component.scss, projects/swimlane/ngx-ui/src/lib/components/section/section.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/section/section.component.ts, src/app/components/sections-page/sections-page.component.html
* Added `aria-controls` and `aria-expanded`
* Adding padding around toggle button
* A11y for headerToggle
_\*required_
=> a11y for sections

projects/swimlane/ngx-ui/src/lib/components/input/input.component.ts
* When using ngx-input with form controls the emitted value was a string.... numeric inputs now emit numbers (again).
* Stop `0` values from being emitted as empty string
* Move bad input check to validators to avoid `ExpressionChangedAfterItHasBeenCheckedError`
_\*required_
=> emit numbers when using form controls

cypress/integration/forms/inputs.spec.ts, package-lock.json, projects/swimlane/ngx-ui/src/lib/components/input/input.component.html, projects/swimlane/ngx-ui/src/lib/components/input/input.component.scss, projects/swimlane/ngx-ui/src/lib/components/input/input.component.spec.ts
password masked
password shown
_\*required_
=> Password Toggle Icon

cypress/integration/forms/inputs.spec.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/input/input.component.html, projects/swimlane/ngx-ui/src/lib/components/input/input.component.scss, projects/swimlane/ngx-ui/src/lib/components/input/input.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/input/input.component.ts, src/app/forms/inputs-page/inputs-page.component.html, src/app/forms/inputs-page/inputs-page.component.ts
Hello there.
I saw #652 and thought I'd have a go at implementing the functionality.
I leveraged the existing `unlockable` input that was already on the `ngx-input` component.
I did make some adjustments to the styles related to toggling password visibility and unlocking input such that both inputs can be used in conjunction if the need arises (i.e. `[unlockable]="true" [passwordToggleEnabled]="true"`). I don't believe these adjustments actually introduce a visual change either.
=> Add support for unlockable password inputs (#652)

cypress/integration/forms/date-inputs.spec.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, projects/swimlane/ngx-ui/src/lib/components/time-display/date-formats.enum.ts, src/app/components/time-display-page/time-display-page.component.html, src/app/forms/datetime-page/datetime-page.component.html
* change default format for timezone date/time to be parsable
* all default formats based on precision
_\*required_
=> fix default formats

cypress/integration/components/time-display.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, projects/swimlane/ngx-ui/src/lib/components/time-display/time-display.component.html, projects/swimlane/ngx-ui/src/lib/components/time-display/time-display.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/time-display/time-display.component.ts, projects/swimlane/ngx-ui/src/lib/enums/date-formats.enum.ts, projects/swimlane/ngx-ui/src/lib/utils/date-formats/default-formats.ts, projects/swimlane/ngx-ui/src/public_api.ts, src/app/components/time-display-page/time-display-page.component.html, src/app/forms/datetime-page/datetime-page.component.html
* consistent formats for `ngx-time`
* react to changes in timezone/precision on ngx-date-time
* simplified and consistent inputs
_\*required_
=> consistant formats for ngx-time

projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.scss, src/app/forms/calendar-page/calendar-page.component.html
* fixed new issue where wide calendar became misaligned
Was:
Is:
_\*required_
=> fix wide calendar

projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss, src/app/forms/selects-page/selects-page.component.html
* Reduce left padding when fill appearance
_\*required_
=> Reduce left padding when fill appearance

projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.scss, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, projects/swimlane/ngx-ui/src/lib/components/time-display/time-display.component.scss, src/app/forms/datetime-page/datetime-page.component.html
* When `[tooltipDisabled]="true"` remove `ngx-date-time--has-popup`
* Use `from-font` for underline thickness
_\*required_
was:
now:
=> remove underline when tooltip is disabled

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/hotkeys/hotkeys.service.ts
Release 37.1.1
Reverting Mousetrap import in HotKeys service
_\*required_
=> (release): 37.1.1

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.html, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts
* When a user is typing a date and an input value changes (e.g. `[hint]`) the display is refresh and user loses current input
* Disable popups when input element has focus.
_\*required_
=> another fix for datetime

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/array-node.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/object-node.component.ts
Changes json editor model update functions to not mutate the existing model, so they can be compatible with ngrx component stores.
_\*required_
=> Make json-editor models immutable

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-input.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss, src/app/forms/selects-page/selects-page.component.html
* fix control alignment
* fix clear position when dropdown is disabled
* use current ngx-ui icons
* move background in fill appearance to avoid saturation issue
* stop propagation on button click
alignment before:
alignment after:
close button before:
close button after:
saturation before:
after:
_\*required_
=> ngx-select updates

projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss, src/app/forms/selects-page/selects-page.component.html
* fix issues were fill appearance was blocking hover and click events for anchors in single selects
* Move special anchor styles to apply to single selects
* Add demo
_\*required_
=> fix fill appearance blocking pointer events in select options

cypress/integration/dialogs/large-format-dialog.spec.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.html, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.html, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.ts, src/app/dialogs/dialog-large-format-page/dialog-large-format-dialog-page.component.html
Adding support for custom templates in the large dialog subtitle section
_\*required_
=> Supporting custom templates for subtitle in large dialog component

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/button/button.component.scss, src/app/forms/buttons-page/buttons-page.component.html, src/app/forms/buttons-page/buttons-page.component.scss, src/app/forms/buttons-page/buttons-page.component.ts
* Don't wrap text, show ellipsis when text is too long
_\*required_
Before:
After:
=> Buttons fix wrap

projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.html
- Only display subtitle container when there is a subtitle, either string or via template.
Before: LFD without subtitle passed
After: LFD without subtitle passed
_\*required_
=> Display subtitle container only when there is subtitle

projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/dropdown/dropdown.component.ts
Added a public method to programmatically close the `NgxDropdown` component. This method can be accessed by creating a `ViewChild` in your Angular component, which references the `NgxDropdown` component.
_\*required_
=> Resolved Open Issue #653

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/ng-package.json, projects/swimlane/ngx-ui/package.json, projects/swimlane/ngx-ui/src/lib/components/input/input.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/property-config/property-config.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/property-config/property-config.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/node-types/object-node.component.ts
- Fix (`ngx-property-config`): Apply button no longer closes all dialogs
- Feature (`ngx-property-config`): Property names and now generated from title and locked until changed
- Feature (`ngx-input`): Now emits `lockChange` even when an input is unlocked
_\*required_
=> Json schema builder

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/node-info/node-info.component.scss
Long name and descriptions now display properly
_\*required_
Before:
After:
=> improvements to JSON editor text displays

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
- Enhancement (`ngx-large-format-dialog-content`): Changing Active tab indicator (blue line) to the header bottom line level
- Fix (`ngx-select`): Tagging option width is not correct
- Fix (`ngx-property-config`): Apply button no longer closes all dialogs
- Fix (`ngx-json-editor-flat`): Long name and descriptions now display properly
- Feature (`ngx-property-config`): When a new property is added (in schema builder mode):
- the property dialog is shown
- the property name is generated from the title
- the property type is editable
- Feature (`ngx-input`): Now emits `lockChange` even when an input is unlocked
- Enhancement: Added webhook icons
- BREAKING (`ngx-property-config`): Type is not editable once a property is added
_\*required_
=> (release): 41.0.0

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.scss
Fixing position of the tab active line of large-format-dialog component
Changing width of header and footer lines of large-format-dialog component
_\*required_
=> Fixing position and header, footer borders width

cypress/e2e/components/json-editor.cy.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/schema-validator.service.ts, src/app/components/json-editor-page/json-editor-page.component.ts
Adding support for binary format properties in json editor (including flat editor). Binary format should render a textbox
Schema
Json editor
Json editor flat
_\*required_
=> Adding support for binary format properties in json editor

src/app/components/sections-page/sections-page.component.html
Hi, I noticed that there's an error in section documentation.
It says to hide toggle I must do
```html
<ngx-section
sectionTitle="Attack Details"
[showToggle]="false"
[headerToggle]="true">
Some Content
</ngx-section>
```
but it appears that [showToggle] is no longer valid attribute of ngx-section. I looked in a code and noticed that in code you used
```html
togglePosition="none"
```
instead. So I changed it in docs and now it's correct ^^
_\*required_
=> Fixed error in section documentation

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Release `42.1.0`, which adds `readonly` support to the `ngx-input` component.
_\*required_
=> (release): 42.1.0

projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts
Resolved issue with `ngx-select` not consistently auto-focusing on the filter input when opened and when filtering is enabled.
_\*required_
=> Resolved issue with select filter not auto-focusing on open

projects/swimlane/ngx-ui/CHANGELOG.md
When I merged this PR https://github.com/swimlane/ngx-ui/pull/899, I failed to pull latest from master and messed up the changelog a bit. Moving this two features under today's 42.1.1 release since on that one is where they were shipped.
_\*required_
=> Update changelog to match released features

cypress/e2e/testing.cy.ts, projects/swimlane/ngx-ui-testing/src/commands.ts
Before:
Assertions attached to a `ngxGetValue` command are retried with the same value.
After:
Assertions attached to a `ngxGetValue` are retried with the latest value each time.
_\*required_
=> retry assertion in ngxGetValue

cypress/e2e/components/calendar.cy.ts, cypress/e2e/forms/date-inputs.cy.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/input/input.component.scss, projects/swimlane/ngx-ui/src/lib/components/select/select.component.scss
Move input label to a position matching design
Before:
After:
_\*required_
=> move input label slightly

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/array-node-flat/array-node-flat.component.html
Ensures json editor flat array nodes will forward `schemaUpdate` events from nested nodes
_\*required_
=> Fix: JSON editor flat array nodes not responding to nested schemaUpdate events

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/property-config/property-config.component.html
When creating an playbook input, of type integer, a visual notification is shown if a non-integer is used.  
https://user-images.githubusercontent.com/57198722/207732727-6692f421-473b-4273-a45f-24c2a4619506.mov
~- [ ] \*Added unit tests~
~- [ ] Added changes to `/projects/swimlane/ngx-ui/CHANGELOG.md` under HEAD (Unreleased)~
~- [ ] Updated the demo page~
_\*required_
=> Spt 14582 update interger playbook input

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html
Resolved issue with JSON Editor component where a node would redraw at the bottom of the list when an existing value was cleared from the `ngx-select`. This was occurring on `Enum` types on the JSON Editor component.
_\*required_
=> JSON Editor: node redraws at bottom of list when value is cleared

projects/swimlane/ngx-ui/src/lib/components/json-editor/schema-validator.service.ts
schema-validator.service.ts: use constructor in declare class to be comptabible for all typescript versions.
fix #931 
_\*required_
=> schema-validator.service.ts: use constructor in declare class

projects/swimlane/ngx-ui/src/lib/components/card/card-avatar/card-avatar.component.html, projects/swimlane/ngx-ui/src/lib/components/card/card-avatar/card-avatar.component.scss, projects/swimlane/ngx-ui/src/lib/components/card/card-avatar/card-avatar.component.ts, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/components/large-format-dialog-header-title/large-format-dialog-header-title.component.scss, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.html, projects/swimlane/ngx-ui/src/lib/components/dialog/large-format/large-format-dialog-content.component.ts, projects/swimlane/ngx-ui/src/lib/directives/resize-observer/resize-observer.directive.spec.ts, src/app/components/card-page/card-page.component.html, src/app/dialogs/dialog-large-format-page/dialog-large-format-dialog-page.component.html
- Updated `ngx-card-avatar` and `ngx-large-format-dialog-content` components with new `@Input()` for enabling the removal of the default white background on images. 
- Updated API documentation `ngx-large-format-dialog-content` component to include new `Input()` and added missing documentation for `ngx-card-avatar` component.
_\*required_
=> Update Card Avatar and Large Format Dialog Content Components to Enable Removal of White Background from Images

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/input/input-autosize.directive.ts, src/app/forms/inputs-page/inputs-page.component.html, src/app/forms/inputs-page/inputs-page.component.ts
fix textarea autosize directive to work with initial value 
_\*required_
=> fix(ngx-input): textarea autosize directive is not considering initial value

cypress/e2e/components/sections.cy.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/section/section.component.html, projects/swimlane/ngx-ui/src/lib/components/section/section.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/section/section.component.ts, src/app/components/sections-page/sections-page.component.html
This fixes a bug that prevented sections from being toggled when clicking the toggle button if both the header toggle and button toggle were enabled
_\*required_
=> Section header and button toggle bug fix

cypress/e2e/components/sections.cy.ts, projects/swimlane/ngx-ui/src/lib/components/section/section.component.ts
This fixes a race condition introduced to the ngx-section tests.
_\*required_
=> Fix ngx-section test race condition

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/package.json
Release PR for version 44.5.0, which adds support for displaying tooltips on the `ngx-select-option` component.
_\*required_
=> (release): 44.5.0

cypress/e2e/components/json-editor.cy.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/node-types/object-node-flat/object-node-flat.component.ts
Remove pre-check for schema property when updating a property name. schemaBuilderMode determines which schema to update, schemaRef or schema
_\*required_
=> fix(object-node-flat-component): Schema property naming in builder mode

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts
Fix focus issue of filterable dropdown.
**Before :**
**After :**
_\*required_
=> fix focus issue of filterable dropdown

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.html, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts, src/app/forms/selects-page/selects-page.component.html
A new event is triggered when the X button is pressed to clear the filter query.
Prettier and Lint changes:
Fixes were applied only to the affected files.
_\*required_
=> ngx-select-dropdown - clearQueryFilter event

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-flat/json-editor-node-flat/json-editor-node-flat.component.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor-node.ts, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.html, projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor/json-editor-node/json-editor-node.component.ts
Datetime input is failing because the datetime input is omitting the seconds, so I use a pipe to resolve this issue.
_\*required_
=> Fix datetime input bug

projects/swimlane/ngx-ui/src/lib/components/json-editor/json-editor.helper.ts
This PR fix a bug caused by the dataTypeMap overwrite, so I create a copy to avoid make changes directly in this variable.
_\*required_
=> fix: repair html input type overwritten

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.html, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.scss, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-time/date-time.component.ts, src/app/forms/datetime-page/datetime-page.component.html, src/app/forms/datetime-page/datetime-page.component.scss, src/app/forms/datetime-page/datetime-page.component.ts
This PR introduces the ability for users to input, view, and persist time with precision up to milliseconds in the DateTime control. This enhancement is crucial for scenarios where precise time tracking is necessary.
_\*required_
=> feat(datetime): support for seconds & milliseconds

projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts
Fixed bug with `ngx-select` component where the dropdown options rendered as `ngx-select-option` components were not being removed from the DOM when the iterable was set to an empty array.
_\*required_
=> Bug fix: dropdown options not cleared for ngx-select component when iterable is set to an empty array

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.ts, projects/swimlane/ngx-ui/src/lib/components/toggle/toggle.component.ts
Adding timeStamp value when emitting change event for ngx-checkbox and ngx-toggle
_\*required_
=> Adding timeStamp when emitting change

projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.ts, projects/swimlane/ngx-ui/src/lib/components/calendar/calender.component.spec.ts
* fix: ux when clicking on same day in calendar range
Fixes an issue when selecting on the same day with recent calendar range changes.
_\*required_
=> Calendar Bugfix

cypress/e2e/forms/checkbox.cy.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.html, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.scss, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.ts, src/app/forms/checkbox-page/checkbox-page.component.html, src/app/forms/checkbox-page/checkbox-page.component.ts
This PR introduces an `indeterminate` state for ngx-checkbox, mirroring the native browser behavior of `input[type="checkbox"]` when put in the same `indeterminate` state. 
In summary, a checkbox should be able to display `indeterminate` regardless of `value`. `indeterminate` should not set `value` (or `checked`), but it should override the look and feel. `indeterminate` should only be set externally and any form handling should account for special cases involving `indeterminate`.  
- Enhancement (`ngx-checkbox`): a new look is available that displays the `indeterminate` state.
- Enhancement (`ngx-checkbox`): new `@Input` named `indeterminate` set to a `boolean`.
- Enhancement (`ngx-checkbox`): implements an `EventEmitter` when `indeterminate` changes.
- Fix (`ngx-checkbox`): position of …
=> Indeterminate Checkbox 

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/checkbox/checkbox.component.ts
Removing the `indeterminate state value validation` in the 'checked' input of the checkbox component
_\*required_
=> Removing validation of indeterminate state from checkbox 'checked' prop

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/filter/filter-select.component.scss, projects/swimlane/ngx-ui/src/lib/components/select/select-dropdown.component.html
This pull request includes a change to the styling of the filter select component. The change modifies the dropdown options to ensure they are fully visible and not constrained by height to remove the multiple scrollbars.
https://github.com/user-attachments/assets/8732a0c5-8a63-45b7-8b98-5cdc56790140
_\*required_
=> Removed the height constraint on the inner container to remove the scrollbar.

cypress/e2e/components/calendar.cy.ts, projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/calendar/calendar.component.scss
Fixes display issue with the Calendar on Firefox by setting the outline property to none instead of auto, ensuring consistent rendering across browsers.
_\*required_
=> calendar fixed on firefox

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.ts, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/services/date-utils.service.ts, projects/swimlane/ngx-ui/src/lib/components/filter/filter.component.scss, src/app/components/filters-page/filters-page.component.html
Added more items in preset list to include week and quarter selection. Bug fix for invalid custom input string
_\*required_
=> Date range preset addition and bugfix

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/column/column/column.component.html, projects/swimlane/ngx-ui/src/lib/components/column/column/column.component.scss, projects/swimlane/ngx-ui/src/lib/components/column/column/column.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/column/column/column.component.ts, projects/swimlane/ngx-ui/src/lib/components/column/column/column.types.ts, projects/swimlane/ngx-ui/src/lib/components/column/columns.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/column/columns.component.ts, src/app/components/column-page/column-page.component.ts
* Breaking: dynamic components use declarative syntax in columns
_\*required_
=> Breaking: ColumnComponent supports new declarative syntax for dynamic components

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/column/column/column.component.html, projects/swimlane/ngx-ui/src/lib/components/column/column/column.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/column/column/column.component.ts, projects/swimlane/ngx-ui/src/lib/components/column/columns.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/column/columns.component.ts, src/app/components/column-page/column-page.component.html
feat: column should emit event when user interacts
fix: remove unused template variable
fix: type definition flaw
fix: issues on demo page
ColumnsComponent now exposes an output named `onColumnChange` that emits an event whenever the user interacts with a tab.
_\*required_
=> feat: Column Events

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/date-range-calendar/date-range-picker.component.ts
Support string or Date input for selectedRange.
https://github.com/user-attachments/assets/7a4c58cc-c2a8-4b34-b7bc-cbe8a6302b8d
_\*required_
=> date-range selected range cancel fix

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/select/select.component.spec.ts, projects/swimlane/ngx-ui/src/lib/components/select/select.component.ts
This is a fix to do not replace the value of the `options` input with the options added in the template. The issue was introduced in the following PR https://github.com/swimlane/ngx-ui/pull/1019
The new behavior will allow to overwrite the value of the `options` input only if the select has options defined in the template.
_\*required_
=> Fix select options replaced when they were bound using the input options

projects/swimlane/ngx-ui/CHANGELOG.md, projects/swimlane/ngx-ui/src/lib/components/filter/filter.component.ts
- Fix: `ngx-filter` now displays the caret when the `multiDimension` input is set to `true` and no values are selected.
_\*required_
=> Ngx-filter: Show caret when multi dimension is enabled and no values are selected
